[package]
name = "parser"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = { version = "3.12.0", features = ["collections"] }
serde = "1.0.157"

[[bin]]
name = "parser"
path = "main.rs"
